version: '3.9'

services:

  nginx-search:
    image: nginx:latest
    container_name: hotel-nginx-search
    volumes:
      - ./nginx/search.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - search-service

  mongo:
    image: mongo:7
    container_name: hotel-mongodb
    ports:
      - "27015:27017"
    volumes:
      - ./db_init.sh:/docker-entrypoint-initdb.d/db_init.sh:ro
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: hotel-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data


  search-service:
    build:
      context: ./search-service
    #    container_name: search-service
    deploy:
      replicas: 1
    depends_on:
      - mongo
      - redis
    environment:
      HOTEL_MONGO_URI: mongodb://10.193.22.20:27015/hotel-app
      REDIS_HOST: 10.193.22.69
  
  nginx-gateway: 
    image: nginx:latest
    container_name: hotel_nginx_gateway
    ports:
      - "3000:80"
    volumes: 
      - ./nginx/gateway.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
     - nginx-search

volumes:
  mongo_data:
  redis_data: