version: '3.9'

services:

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - booking-service
      - search-service
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: hotel-mongodb
    ports:
      - "27015:27017"
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: hotel-redis
    ports:
        - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data

  user-service:
    build:
      context: ./user-service
#    container_name: user-service
    deploy:
      replicas: 2
    depends_on:
      - mongo
    environment:
      HOTEL_MONGO_URI: mongodb://mongo:27017/hoteldb

  booking-service:
    build:
      context: ./booking-service
#    container_name: booking-service
    deploy:
      replicas: 2
    depends_on:
      - mongo
    environment:
      HOTEL_MONGO_URI: mongodb://mongo:27017/hoteldb

  search-service:
    build:
      context: ./search-service
#    container_name: search-service
    deploy:
      replicas: 2
    depends_on:
      - mongo
      - redis
    environment:
      HOTEL_MONGO_URI: mongodb://mongo:27017/hoteldb
      REDIS_HOST: redis

volumes:
  mongo_data:
  redis_data: